Handle chars "$" and "\" in job output if formatter is used
If the output of a command contains the chars "$" or "\" and the
formatter is used, the characters "$" and "\" are not handled. Hence,
an exception is thrown:
java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
	at org.rundeck.client.util.Format.format(Format.java:44)